-- Make booking_reference optional for inserts since it's auto-generated by trigger
ALTER TABLE new_bookings ALTER COLUMN booking_reference SET DEFAULT 'TH' || LPAD(EXTRACT(EPOCH FROM NOW())::TEXT, 10, '0') || LPAD(floor(random() * 1000)::TEXT, 3, '0');

-- Ensure the trigger exists for auto-generating booking reference
CREATE OR REPLACE FUNCTION generate_booking_reference_new()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.booking_reference IS NULL OR NEW.booking_reference = '' THEN
    NEW.booking_reference = 'TH' || LPAD(EXTRACT(EPOCH FROM NOW())::TEXT, 10, '0') || LPAD(floor(random() * 1000)::TEXT, 3, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger if it doesn't exist
DROP TRIGGER IF EXISTS trigger_generate_booking_reference_new ON new_bookings;
CREATE TRIGGER trigger_generate_booking_reference_new
  BEFORE INSERT ON new_bookings
  FOR EACH ROW
  EXECUTE FUNCTION generate_booking_reference_new();